src/lib.rs

RecordIterator is not exposed on the public interface, preventing e.g. having a RecordIterator as a struct field:
`struct MyStruct {
dbase::RecordIterator<BufReader<File>>,
}`
This pull requests adds RecordIterator to the exposed interface on the crate.

Add RecordIterator to public interface.

---

src/header.rs
src/reading.rs
src/record/field.rs
src/record/mod.rs

I was trying to update `shapefile` to use `dbase` 0.1.0 but in debugging some issue there, I noticed that `Reader` wasn't clone but could be.
I also fixed 2 minor things that Clippy pointed out.
If this pull request is accepted, it may be worth it to push out a new version of the crate (#9 isn't available on Cargo, for example)

Reader is now Clone

---

.gitignore
src/reading.rs

Fixes #11 by ensuring the source cursor for a new reader is at position = header.offset_to_first_record. Previously, this wasn't guaranteed.

fix reader offset issue

---

CHANGELOG.md
src/lib.rs
src/writing.rs
tests/test_serde.rs
tests/tests.rs

Refactor the TableWriter to be able to write one record at a time.
Add a `write_record` method to write one record (callable many time)
Rename `write` to `write_records` and change its arguments from `&[Record]` to `IntoIterator<&Record>`

Allow the writing of records one  by one

---

src/reading.rs
src/record/field.rs

This commit improves the way the values are read from the dbf files
improving the speed of the file processing by almost 3 times.
The key points of improvement:
* Removes `Vector::resize()` call in `read_string_of_len` function.
Using `vec![0; len]` instead gives significant improvement.
* Instead of using `String::trim()` on the read values (to remove
spaces) we first skip the empty bytes, and then convert the value
into the string. Removing `trim` calls improves performance almost
doublefold.
* Using unchecked indexing on the vector when trimming spaces
provides ~30% improvement in comparison to the safe version.
Using unsafe here is not strictly necessary, but the logic in
the unsafe block is quite straitforward so it should be ok.
Overall in my case reading a 500 MiB dbf file takes:
* …

Improves performance of reading large dbfs

---

src/reading.rs
src/record/field.rs

The RecordIterator now has a buffer where we first read the whole record into it
before handing it to the FieldIterator.
This improve reading performance by substantial amount, for a 1.3GB file,
without this change it take ~1min10 secs to read the file, with this change
it takes ~28 secs
related to #22

Use a buffer to read record data

---

src/writing.rs

We did not account for the `deletion flag` flag that is one byte long
and present before every record in the record size written in the header.
Without this our files are invalid
Fixes #26

Fix record size written in header

---

CHANGELOG.md
Cargo.toml
src/header.rs
src/lib.rs
src/reading.rs
src/record/field.rs
src/record/mod.rs
src/writing.rs

Fixes #34 
This will require a major version bump.
If we want to keep compatibility for users who are stuck on `chrono`, I could imagine putting in a `chrono` feature flag that would gate the relevant impls.

replace chrono with time; fix some things clippy was upset about

---

src/encoding.rs
src/error.rs
src/lib.rs
src/reading.rs
src/record/field.rs
src/ser.rs
src/writing.rs
tests/test_serde.rs
tests/tests.rs

- Add support for writing with given encoding, code page support via `yore` crate
- Fix writing of visual fox pro file (the backlink was not written, we actually don't write it, but we pad with zeros)
- Breaking changes since the Encoding appears in type signatures

Add support for writing file with a given encoding

---

src/de.rs
src/encoding.rs
src/error.rs
src/header.rs
src/lib.rs
src/reading.rs
src/ser.rs
src/writing.rs
tests/test_serde.rs
tests/tests.rs

This removes the encoding from the type parameters.
The encoding is used inernally as a `Box<dyn Encoding>`, allowing to keep the current API, and avoiding to
complexify it.
It also allows to use the code page mark written in the header to auto select the encoding after the file is opened.

Remove encoding from type parameters

---

src/record/field.rs

This small change makes `Date`s `new` function be callable in `const` contexts. This is useful when writing tests or in other contexts where record data may be statically created.

Make 'Date's const-constructable

---

src/lib.rs

added support to custom visibility of structs and fields using the dbase_record macro

keep visibility on dbase_record macro

---

Cargo.toml
examples/file.rs
src/de.rs
src/file.rs
src/header.rs
src/lib.rs
src/reading.rs
src/writing.rs
tests/test_file.rs
tests/tests.rs

This new dbase::File struct allows to open a .dbf file in read or write or read+write mode.
This allows to read and modify a file
without having to first read eveything using dbase::Reader, make in memory modifications then write using dbase::TableWriter.
close #28

add first iteration of dbase::File

---

src/encoding.rs

I have a dbase file which I would like to read that uses ASCIIZ encoding for the field names (ASCII terminated by "\0" byte). Currently when reading this file, the crate panics with a "Not ASCII" error because the bytes following "\0" are garbage.
This change will read the field name only up to the first "\0" byte, which solves the issue.
These are the docs where I found the detail about the ASCIIZ encoding: https://www.fileformat.info/format/corion-dbase-iii.htm
Let me know if you would suggest any changes.
Cheers

support ASCIIZ encoding of field names

---

.github/workflows/rust.yml
Cargo.toml
examples/datafusion.rs
src/datafusion.rs
src/encoding.rs
src/field/types.rs
src/lib.rs

Create `DbaseTable` struct which implements datafusions `TableProvider` trait. This allows querying dbase tables using SQL syntax. This is implemented as an optional feature.
I'm pretty new to Rust so let me know if you would suggest any changes or improvements, or have any other feedback.
Cheers

add datafusion support with example

---

src/reading.rs

I'm currently writing a script that writes data to stdout, but the debug text from this causes issues. It looks like it may have been left there by mistake, so this PR removes it.
Cheers

remove extraneous debug macro

---

src/field/types.rs
src/file.rs
src/header.rs
src/lib.rs
src/reading.rs
tests/test_file.rs
tests/tests.rs

Adds a `ReadingOption` that enables to choose how character fields should be trimmed.
Addresses #56 
~~- [ ] Put the encoding as a reading option ?~~
~~- [ ] Should options be per field ? ->  more complex to do~~

Add TrimOption

---

src/lib.rs
src/reading.rs

I have cases where I need to read a dbf file with its memo file, but they are not available from a path (i.e from S3 or similar non-local-fs storage). I can still access them, but I need to be able to create a reader and attaching the memo source, and this seems convenient!
Thoughts?

Adding a builder for Reader

---

src/datafusion.rs
src/field/types.rs

Hi @tmontaigu,
I ran in to an error reading a dbase file with memo fields, so I have created this PR to fix. Changes are:
- raise error with datafusion if there is an error parsing a record. Previously these would be silently skipped, because I had assumed these cases were just empty records when they are not. 
- use `TrimOption::BeginEnd` instead of `TrimOption::End` when trying to get position in memo file. The dbase file I'm using had `trimmed_value` similar to the following, which would not be trimmed on the left and would then throw an error when parsing:
```
(10) &[32, 32, 32, 32, 32, 32, 32, 32, 32, 48]
```
Cheers

fix issue reading memo files with leading spaces

---

src/datafusion.rs

When reading memo fields I would get strings like `\u{57}\u{20}...` etc. because of the `escape_unicode()` function being used. This PR fixes this so that comprehensible text is returned.
Note that the reason for using the `escape_` function for memo fields in the first place is because they often contain newlines and other characters which interfere with CSV writing and printing when using datafusion. So, this is converting them to literal `\n`, `\t` etc.

datafusion: use appropriate function to escape special chars in memo fields

---

src/field/mod.rs
src/file.rs
src/lib.rs
src/memo.rs
src/reading.rs

There is still some unwraps left in `File::record` function.
The choice is wether to change those unwraps and make `File::record` return a `Option<Result<Record, Error>>` but it makes
the caller do 2 unwraps (unless using while let Some)
or delay the seek / reading of data until either some FieldRef::write or read is called

Faster file

---

src/datafusion.rs

- switch datafusion from reader to buffered file for performance.

datafusion: use buffered file

---

src/file.rs

Hi, I'm interested in extending the functionality of dbase-rs to make it runnable on the web. My use case is that I'm working on a hobby project that targets the web and needs to be able to read in shapefiles, which is a multifile format with a dbase component. Would you be happy to accept a PR enabling this? 
Below is a more involved explanation of what this PR attempts to achieve. I don't have much knowledge in this domain so I might have made some mistakes. I've included some links for reference.
Running dbase-rs on the web can be achieved with WebAssembly but there seem to be 2 different compilation targets, neither of which target the web specifically:
- `wasm32-unknown-unknown`
- `wasm32-wasi` / `wasm32-wasip2`
The former does not make any assumptions about the platform it will run …

support the wasm32-wasi target

---

Cargo.toml
src/field/types.rs
src/lib.rs

This was described as an option in to add back behind a feature in  https://github.com/tmontaigu/dbase-rs/pull/35, which this PR does.

Implements conversions of Date, Time and DateTime structs from and into chrono NaiveDate, NaiveTime and NaiveDateTime structs.

---

Cargo.toml
src/file.rs
tests/test_bugged_file_sync.rs

The implementation of BufReadWriteFile in order
to have buffered read and write on a std::fs::File was made in a 'hacky' using 2 files and 1 BufReader and a BufWriter, this impl was not completely correct.
Indeed there was a synchronization bug that was happening in release build but not in debug build because a debug_assert called a method that would force the synchronization.
So we replace this by BufReaderWriter type from the bufrw crate which should not properly implement buffered read + write

Use bufrw for the BufReadWriteFile
